version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffee-shop-api
    ports:
      - "8080:80"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]

  db:
    image: postgres
    container_name: coffee-shop-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coffee-shop
      PGDATA: /data/postgres
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    ports:
        - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres:
  pgadmin-data: